#!/usr/bin/env python3
"""
Execute a GitHub Actions workflow (or standalone action.yml) locally using pixi.

Flow:
  1. Parse the workflow YAML and collect all `uses:` action references.
  2. Generate rattler-build recipes for any action that doesn't already have one.
  3. Build all recipes into a local conda channel (./channel/).
  4. Write a pixi.toml that lists every action package and points at the local channel.
  5. Run `pixi install` to lock the environment.
  6. Execute each job step in order, using the pixi environment's prefix to locate
     installed action files.

Supported action types:
  - node16 / node20 / node22  (most common)
  - composite                 (calls other actions recursively)
  - run steps                 (plain shell commands)

Not supported:
  - docker actions
  - service containers
  - matrix strategies
  - reusable workflows

Usage:
    python executor.py example-workflow.yml
    python executor.py example-workflow.yml --job build
    python executor.py example-workflow.yml --build-only
    python executor.py example-workflow.yml --no-rebuild
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml  (or: pixi install)")

from generate_recipe import (
    action_type,
    generate_recipe,
    node_version,
    package_name,
    normalize_version,
    parse_action_ref,
)

# ---------------------------------------------------------------------------
# Constants / paths
# ---------------------------------------------------------------------------

RECIPES_DIR = Path("recipes")
CHANNEL_DIR = Path("channel")
RUNNER_DIR = Path(".runner")
PIXI_TOML = RUNNER_DIR / "pixi.toml"
PIXI_LOCK = RUNNER_DIR / "pixi.lock"


# ---------------------------------------------------------------------------
# Workflow parsing
# ---------------------------------------------------------------------------

def load_workflow(path: Path) -> dict[str, Any]:
    with path.open() as f:
        return yaml.safe_load(f)  # type: ignore[no-any-return]


def collect_action_refs(workflow: dict[str, Any]) -> list[str]:
    """Return all distinct `uses:` values from every job's steps."""
    refs: list[str] = []
    jobs = workflow.get("jobs", {})
    for job in jobs.values():
        for step in job.get("steps", []):
            uses = step.get("uses")
            if uses and "@" in uses:
                # Normalise: some refs use ./ (local actions) - skip those
                if not uses.startswith("./"):
                    refs.append(uses)
    return list(dict.fromkeys(refs))  # deduplicate, preserve order


# ---------------------------------------------------------------------------
# Recipe / build helpers
# ---------------------------------------------------------------------------

def ensure_recipe(action_ref: str, force: bool = False) -> Path:
    """Generate a recipe for *action_ref* if one doesn't already exist."""
    owner, repo, ref = parse_action_ref(action_ref)
    pkg = package_name(owner, repo)
    recipe_path = RECIPES_DIR / pkg / "recipe.yaml"
    if recipe_path.exists() and not force:
        print(f"  Recipe already exists: {recipe_path}")
        return recipe_path
    return generate_recipe(action_ref, RECIPES_DIR)


def build_recipe(recipe_path: Path, channel_dir: Path) -> bool:
    """Run rattler-build for *recipe_path*, outputting packages into *channel_dir*."""
    channel_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "rattler-build", "build",
        "--recipe", str(recipe_path),
        "--output-dir", str(channel_dir),
        "--no-test",  # skip tests during bulk-build; run them explicitly if needed
    ]
    print(f"  Building: {recipe_path}")
    result = subprocess.run(cmd, capture_output=False)
    if result.returncode != 0:
        print(f"  ERROR: rattler-build failed for {recipe_path}", file=sys.stderr)
        return False
    return True


def find_built_package(pkg: str, channel_dir: Path) -> Path | None:
    """Return the path to the built .conda file for *pkg*, if any."""
    for p in channel_dir.rglob(f"{pkg}-*.conda"):
        return p
    for p in channel_dir.rglob(f"{pkg}-*.tar.bz2"):
        return p
    return None


# ---------------------------------------------------------------------------
# pixi.toml generation
# ---------------------------------------------------------------------------

PIXI_TOML_TEMPLATE = """\
# Auto-generated by executor.py — do not edit by hand.
[project]
name = "gh-actions-runner"
channels = [
    "file://{channel_abs}",
    "conda-forge",
]
platforms = ["{platform}"]

[dependencies]
{deps}
"""


def detect_platform() -> str:
    import platform as _platform
    system = _platform.system().lower()
    machine = _platform.machine().lower()
    if system == "linux":
        arch = "x86_64" if machine in ("x86_64", "amd64") else "aarch64"
        return f"linux-{arch.replace('x86_64','64').replace('aarch64','aarch64')}"
    if system == "darwin":
        return "osx-arm64" if machine == "arm64" else "osx-64"
    if system == "windows":
        return "win-64"
    return "linux-64"


def write_pixi_toml(action_refs: list[str], channel_dir: Path) -> None:
    RUNNER_DIR.mkdir(parents=True, exist_ok=True)
    channel_abs = channel_dir.resolve()
    platform = detect_platform()

    dep_lines: list[str] = []
    for ref in action_refs:
        owner, repo, git_ref = parse_action_ref(ref)
        pkg = package_name(owner, repo)
        try:
            ver = normalize_version(git_ref)
            # Pin to exact major.minor.patch but allow build string variation
            dep_lines.append(f'{pkg} = "{ver}.*"')
        except ValueError:
            # Non-semver ref (branch / SHA) — accept any version
            dep_lines.append(f'{pkg} = "*"')

    content = PIXI_TOML_TEMPLATE.format(
        channel_abs=channel_abs,
        platform=platform,
        deps="\n".join(dep_lines),
    )
    PIXI_TOML.write_text(content)
    print(f"Wrote {PIXI_TOML}")


# ---------------------------------------------------------------------------
# Pixi install / prefix resolution
# ---------------------------------------------------------------------------

def pixi_install() -> Path:
    """Run `pixi install` in RUNNER_DIR and return the env prefix."""
    print("Running `pixi install`...")
    subprocess.run(
        ["pixi", "install"],
        cwd=RUNNER_DIR,
        check=True,
    )
    # pixi installs to .pixi/envs/default relative to the project dir
    prefix = RUNNER_DIR / ".pixi" / "envs" / "default"
    if not prefix.exists():
        raise RuntimeError(f"Expected pixi env prefix at {prefix} but it does not exist.")
    return prefix


def pixi_env_prefix(runner_dir: Path = RUNNER_DIR) -> Path:
    """Return the existing pixi env prefix without re-installing."""
    return runner_dir / ".pixi" / "envs" / "default"


# ---------------------------------------------------------------------------
# Workflow command parsing  (::set-output::, GITHUB_OUTPUT file, etc.)
# ---------------------------------------------------------------------------

# Map from step id → {output_name: value}
OutputMap = dict[str, dict[str, str]]

WORKFLOW_CMD_RE = re.compile(
    r"^::(?P<cmd>[a-z-]+)(?:\s+(?P<params>[^:]*))?::(?P<value>.*)$"
)


def parse_workflow_commands(line: str, step_id: str, outputs: OutputMap) -> None:
    """Handle a single line of workflow command output."""
    m = WORKFLOW_CMD_RE.match(line.rstrip())
    if not m:
        return
    cmd = m.group("cmd")
    params_str = m.group("params") or ""
    value = m.group("value")

    params: dict[str, str] = {}
    for part in params_str.split(","):
        if "=" in part:
            k, v = part.split("=", 1)
            params[k.strip()] = v.strip()

    if cmd == "set-output":
        name = params.get("name", "")
        if name:
            outputs.setdefault(step_id, {})[name] = value
    elif cmd in ("error", "warning", "notice", "debug"):
        tag = cmd.upper()
        print(f"[{tag}] {value}")


def read_multiline_file(path: str) -> dict[str, str]:
    """Parse a GITHUB_OUTPUT / GITHUB_ENV style file (key<<delimiter / value)."""
    result: dict[str, str] = {}
    if not path or not os.path.exists(path):
        return result
    with open(path) as f:
        lines = f.readlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip("\n")
        if "<<" in line:
            key, delimiter = line.split("<<", 1)
            delimiter = delimiter.strip()
            i += 1
            val_lines = []
            while i < len(lines) and lines[i].rstrip("\n") != delimiter:
                val_lines.append(lines[i])
                i += 1
            result[key] = "".join(val_lines).rstrip("\n")
        elif "=" in line:
            key, val = line.split("=", 1)
            result[key] = val
        i += 1
    return result


# ---------------------------------------------------------------------------
# Step execution
# ---------------------------------------------------------------------------

class StepContext:
    def __init__(
        self,
        env_prefix: Path,
        workspace: Path,
        outputs: OutputMap,
        extra_env: dict[str, str],
    ) -> None:
        self.env_prefix = env_prefix
        self.workspace = workspace
        self.outputs = outputs
        self.extra_env = extra_env  # accumulated from previous steps

    def resolve_expr(self, text: str) -> str:
        """Very basic ${{ }} expression substitution."""
        def _sub(m: re.Match) -> str:
            expr = m.group(1).strip()
            # steps.<id>.outputs.<name>
            sm = re.match(r"steps\.(\w+)\.outputs\.(\w+)", expr)
            if sm:
                sid, oname = sm.group(1), sm.group(2)
                return self.outputs.get(sid, {}).get(oname, "")
            # env.<name>
            em = re.match(r"env\.(\w+)", expr)
            if em:
                return self.extra_env.get(em.group(1), os.environ.get(em.group(1), ""))
            return m.group(0)  # leave unknown expressions as-is

        return re.sub(r"\$\{\{\s*(.*?)\s*\}\}", _sub, text)

    def build_env(
        self,
        step_env: dict[str, str] | None,
        inputs: dict[str, str] | None,
        step_id: str,
    ) -> tuple[dict[str, str], str, str, str]:
        """Return (env_dict, github_output_file, github_env_file, github_path_file)."""
        tmp_output = tempfile.NamedTemporaryFile(
            prefix="gh_output_", suffix=".env", delete=False
        )
        tmp_output.close()
        tmp_gh_env = tempfile.NamedTemporaryFile(
            prefix="gh_env_", suffix=".env", delete=False
        )
        tmp_gh_env.close()
        tmp_gh_path = tempfile.NamedTemporaryFile(
            prefix="gh_path_", suffix=".txt", delete=False
        )
        tmp_gh_path.close()

        env = {
            **os.environ,
            **self.extra_env,
            # Paths
            "GITHUB_WORKSPACE": str(self.workspace),
            "GITHUB_ACTION": step_id,
            "GITHUB_ACTION_PATH": "",  # filled in by callers for `uses` steps
            # Workflow command files
            "GITHUB_OUTPUT": tmp_output.name,
            "GITHUB_ENV": tmp_gh_env.name,
            "GITHUB_PATH": tmp_gh_path.name,
            "GITHUB_STEP_SUMMARY": os.devnull,
            # Make the pixi env's bin visible
            "PATH": str(self.env_prefix / "bin") + os.pathsep + os.environ.get("PATH", ""),
        }

        # Merge step-level env (expressions resolved)
        for k, v in (step_env or {}).items():
            env[k] = self.resolve_expr(str(v))

        # Map `with:` inputs to INPUT_* env vars
        for k, v in (inputs or {}).items():
            env[f"INPUT_{k.upper().replace('-', '_')}"] = self.resolve_expr(str(v))

        return env, tmp_output.name, tmp_gh_env.name, tmp_gh_path.name

    def collect_outputs_from_files(
        self,
        step_id: str,
        github_output_file: str,
        github_env_file: str,
        github_path_file: str,
    ) -> None:
        """Read GITHUB_OUTPUT / GITHUB_ENV / GITHUB_PATH files after a step runs."""
        step_outputs = read_multiline_file(github_output_file)
        if step_outputs:
            self.outputs.setdefault(step_id, {}).update(step_outputs)

        new_env = read_multiline_file(github_env_file)
        self.extra_env.update(new_env)

        path_additions = Path(github_path_file).read_text().strip() if os.path.exists(github_path_file) else ""
        if path_additions:
            for p in path_additions.splitlines():
                p = p.strip()
                if p:
                    self.extra_env["PATH"] = p + os.pathsep + self.extra_env.get("PATH", os.environ.get("PATH", ""))

        # Clean up temp files
        for f in (github_output_file, github_env_file, github_path_file):
            try:
                os.unlink(f)
            except OSError:
                pass


def run_uses_step(
    step: dict[str, Any],
    ctx: StepContext,
) -> bool:
    """Execute a `uses:` step. Returns True on success."""
    action_ref: str = step["uses"]
    step_id: str = step.get("id", action_ref.replace("/", "-").replace("@", "-"))
    inputs: dict[str, str] = {k: str(v) for k, v in (step.get("with") or {}).items()}

    owner, repo, ref = parse_action_ref(action_ref)
    action_dir = ctx.env_prefix / "share" / "gh-actions" / owner / repo

    if not action_dir.exists():
        print(
            f"  ERROR: Action directory not found: {action_dir}\n"
            f"  Did you run `pixi install` after building the package?",
            file=sys.stderr,
        )
        return False

    # Read the installed action.yml
    meta_path = None
    for candidate in ("action.yml", "action.yaml"):
        p = action_dir / candidate
        if p.exists():
            meta_path = p
            break
    if meta_path is None:
        print(f"  ERROR: No action.yml found in {action_dir}", file=sys.stderr)
        return False

    with meta_path.open() as f:
        meta: dict[str, Any] = yaml.safe_load(f)

    using = action_type(meta)
    env, gh_out, gh_env, gh_path = ctx.build_env(step.get("env"), inputs, step_id)
    env["GITHUB_ACTION_PATH"] = str(action_dir)

    print(f"  [{step_id}] Running action {action_ref} (type={using})")

    try:
        node_v = node_version(using)
        if node_v is not None:
            return _run_node_action(meta, action_dir, env, ctx, step_id, gh_out, gh_env, gh_path)
        elif using == "composite":
            return _run_composite_action(meta, action_dir, ctx, step_id, inputs)
        else:
            print(f"  SKIP: unsupported action type '{using}' for {action_ref}", file=sys.stderr)
            return True  # don't fail the whole workflow for unsupported types
    finally:
        ctx.collect_outputs_from_files(step_id, gh_out, gh_env, gh_path)


def _run_node_action(
    meta: dict[str, Any],
    action_dir: Path,
    env: dict[str, str],
    ctx: StepContext,
    step_id: str,
    gh_out: str,
    gh_env: str,
    gh_path: str,
) -> bool:
    main_rel: str = meta["runs"].get("main", "dist/index.js")
    main_path = action_dir / main_rel

    if not main_path.exists():
        print(f"  ERROR: main entry point not found: {main_path}", file=sys.stderr)
        return False

    node_bin = shutil.which("node", path=env.get("PATH", ""))
    if node_bin is None:
        print("  ERROR: 'node' not found on PATH. Is nodejs in the pixi env?", file=sys.stderr)
        return False

    proc = subprocess.Popen(
        [node_bin, str(main_path)],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    outputs: OutputMap = {}
    assert proc.stdout is not None

    def _stream() -> None:
        for line in proc.stdout:  # type: ignore[union-attr]
            line = line.rstrip("\n")
            parse_workflow_commands(line, step_id, outputs)
            print(f"    {line}")

    t = threading.Thread(target=_stream, daemon=True)
    t.start()
    proc.wait()
    t.join()

    # Merge inline-captured outputs (legacy ::set-output::) into ctx
    for sid, outs in outputs.items():
        ctx.outputs.setdefault(sid, {}).update(outs)

    if proc.returncode != 0:
        print(f"  ERROR: action exited with code {proc.returncode}", file=sys.stderr)
        return False
    return True


def _run_composite_action(
    meta: dict[str, Any],
    action_dir: Path,
    ctx: StepContext,
    step_id: str,
    inputs: dict[str, str],
) -> bool:
    steps = meta.get("runs", {}).get("steps", [])
    print(f"  Running composite action ({len(steps)} steps)")
    for sub_step in steps:
        ok = execute_step(sub_step, ctx)
        if not ok:
            continue_on_error = sub_step.get("continue-on-error", False)
            if not continue_on_error:
                return False
    return True


def run_run_step(step: dict[str, Any], ctx: StepContext) -> bool:
    """Execute a `run:` step (plain shell command)."""
    step_id: str = step.get("id", f"run-{id(step)}")
    script: str = ctx.resolve_expr(step["run"])
    shell: str = step.get("shell", "bash")
    env, gh_out, gh_env, gh_path = ctx.build_env(step.get("env"), None, step_id)

    name = step.get("name", script.splitlines()[0][:60])
    print(f"  [{step_id}] run: {name}")

    if shell in ("bash", "sh"):
        cmd = [shell, "-e", "-o", "pipefail", "-c", script]
    elif shell == "pwsh":
        cmd = ["pwsh", "-Command", script]
    else:
        cmd = [shell, "-c", script]

    result = subprocess.run(cmd, env=env, cwd=str(ctx.workspace))

    ctx.collect_outputs_from_files(step_id, gh_out, gh_env, gh_path)

    if result.returncode != 0:
        print(f"  ERROR: step exited with code {result.returncode}", file=sys.stderr)
        return False
    return True


def execute_step(step: dict[str, Any], ctx: StepContext) -> bool:
    """Dispatch a single step to the correct runner."""
    # Evaluate `if:` condition (basic support)
    condition = step.get("if")
    if condition is not None:
        resolved = ctx.resolve_expr(str(condition))
        # Treat empty string, "false", "0" as falsy
        if resolved.lower() in ("false", "0", ""):
            step_id = step.get("id", "")
            print(f"  [SKIP] step '{step.get('name', step_id)}' (if condition false)")
            return True

    if "uses" in step:
        return run_uses_step(step, ctx)
    elif "run" in step:
        return run_run_step(step, ctx)
    else:
        print(f"  [SKIP] step has neither 'uses' nor 'run': {step}")
        return True


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def prepare_environment(
    action_refs: list[str],
    rebuild: bool,
) -> Path:
    """
    Generate recipes, build packages, write pixi.toml, run pixi install.
    Returns the pixi env prefix.
    """
    # 1. Generate missing recipes
    print(f"\n=== Step 1: Generate recipes for {len(action_refs)} action(s) ===")
    for ref in action_refs:
        ensure_recipe(ref, force=False)

    # 2. Build packages into local channel
    print(f"\n=== Step 2: Build packages into {CHANNEL_DIR}/ ===")
    for ref in action_refs:
        owner, repo, git_ref = parse_action_ref(ref)
        pkg = package_name(owner, repo)
        recipe_path = RECIPES_DIR / pkg / "recipe.yaml"

        if not recipe_path.exists():
            print(f"  ERROR: Recipe missing for {ref}", file=sys.stderr)
            continue

        if not rebuild and find_built_package(pkg, CHANNEL_DIR) is not None:
            print(f"  Already built: {pkg}")
            continue

        build_recipe(recipe_path, CHANNEL_DIR)

    # 3. Write pixi.toml
    print(f"\n=== Step 3: Write {PIXI_TOML} ===")
    write_pixi_toml(action_refs, CHANNEL_DIR)

    # 4. pixi install
    print(f"\n=== Step 4: pixi install ===")
    return pixi_install()


def run_workflow(
    workflow_path: Path,
    job_name: str | None,
    workspace: Path,
    env_prefix: Path,
) -> None:
    workflow = load_workflow(workflow_path)
    jobs: dict[str, Any] = workflow.get("jobs", {})

    if job_name:
        if job_name not in jobs:
            sys.exit(f"Job '{job_name}' not found in workflow. Available: {list(jobs)}")
        jobs = {job_name: jobs[job_name]}

    outputs: OutputMap = {}
    extra_env: dict[str, str] = {}

    # Merge top-level `env:` from workflow
    for k, v in (workflow.get("env") or {}).items():
        extra_env[k] = str(v)

    for jname, job in jobs.items():
        print(f"\n{'='*60}")
        print(f"JOB: {jname}")
        print(f"{'='*60}")

        # Merge job-level env
        job_env = {**extra_env}
        for k, v in (job.get("env") or {}).items():
            job_env[k] = str(v)

        ctx = StepContext(
            env_prefix=env_prefix,
            workspace=workspace,
            outputs=outputs,
            extra_env=job_env,
        )

        steps = job.get("steps", [])
        for i, step in enumerate(steps):
            name = step.get("name", step.get("uses", step.get("run", "")[:40]))
            print(f"\n--- Step {i+1}: {name} ---")
            ok = execute_step(step, ctx)
            if not ok:
                coe = step.get("continue-on-error", False)
                if not coe:
                    print(f"\nWorkflow failed at step: {name}", file=sys.stderr)
                    sys.exit(1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Execute a GitHub Actions workflow locally using pixi."
    )
    parser.add_argument(
        "workflow",
        type=Path,
        nargs="?",
        help="Path to the workflow YAML file (e.g. example-workflow.yml)",
    )
    parser.add_argument(
        "--job",
        help="Run only this specific job (default: all jobs)",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path.cwd(),
        help="GITHUB_WORKSPACE directory (default: current dir)",
    )
    parser.add_argument(
        "--build-only",
        action="store_true",
        help="Generate recipes and build packages, but do not execute the workflow",
    )
    parser.add_argument(
        "--no-rebuild",
        action="store_true",
        help="Skip building packages that are already present in ./channel/",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip recipe generation and building entirely (assume env is already set up)",
    )
    args = parser.parse_args()

    if args.workflow is None and not args.build_only:
        parser.error("A workflow file is required unless --build-only is set.")

    if args.build_only:
        # Collect refs from all recipes/ subdirs
        refs: list[str] = []
        for recipe_yaml in RECIPES_DIR.rglob("recipe.yaml"):
            import yaml as _yaml
            with recipe_yaml.open() as f:
                r = _yaml.safe_load(f)
            ctx_block = r.get("context", {})
            owner = ctx_block.get("owner")
            repo = ctx_block.get("repo")
            version = ctx_block.get("version")
            if owner and repo and version:
                refs.append(f"{owner}/{repo}@v{version}")
        if not refs:
            print("No recipes found in ./recipes/. Run generate_recipe.py first.")
            return
        prepare_environment(refs, rebuild=not args.no_rebuild)
        print("\nDone. Environment is ready.")
        return

    workflow = load_workflow(args.workflow)
    action_refs = collect_action_refs(workflow)

    print(f"Found {len(action_refs)} action(s) in {args.workflow}:")
    for ref in action_refs:
        print(f"  {ref}")

    if not action_refs:
        print("No `uses:` steps found. Nothing to install.")
        env_prefix = pixi_env_prefix() if PIXI_TOML.exists() else Path("/")
    elif args.skip_build:
        print("\nSkipping build (--skip-build). Using existing pixi environment.")
        env_prefix = pixi_env_prefix()
        if not env_prefix.exists():
            sys.exit(f"Pixi env not found at {env_prefix}. Run without --skip-build first.")
    else:
        env_prefix = prepare_environment(action_refs, rebuild=not args.no_rebuild)

    print(f"\n=== Executing workflow: {args.workflow} ===")
    run_workflow(
        workflow_path=args.workflow,
        job_name=args.job,
        workspace=args.workspace.resolve(),
        env_prefix=env_prefix,
    )
    print("\nWorkflow complete.")


if __name__ == "__main__":
    main()
