#!/usr/bin/env bash
# CLI entry point for actions/checkout
# Generated by generate_recipe.py — do not edit by hand.
#
# Inputs can be supplied as (highest precedence first):
#   key=value positional args:  checkout token=ghp_xxx fetch-depth=0
#   JSON string:                checkout --inputs-json '{"token":"ghp_xxx"}'
#   JSON/YAML file:             checkout --inputs-file inputs.yml
#   Environment variables:      INPUT_TOKEN=ghp_xxx checkout
set -euo pipefail

# ---- constants baked in at generate time ----
_OWNER='actions'
_REPO='checkout'
_MAIN_SCRIPT='dist/index.js'
_POST_SCRIPT='dist/post.js'

# Locate the conda prefix: this script lives at $PREFIX/bin/<name>
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_PREFIX="$(dirname "$_SCRIPT_DIR")"
ACTION_DIR="$_PREFIX/share/gh-actions/$_OWNER/$_REPO"

_post=0
_workspace="${GITHUB_WORKSPACE:-$(pwd)}"
_extra_env=()
_json_inputs=''
_file_inputs=''

_usage() {
  echo "Usage: checkout [key=value ...] [OPTIONS]"
  echo ""
  echo "Run GitHub Action: Checkout"
  echo "Check out a Git repository at a particular version"
  echo ""
  echo "Inputs  (key=value positional args or INPUT_KEY env vars):"
  echo "  repository=    Repository name with owner (required if not in env)"
  echo "      The repository (owner/repo) to check out."
  echo "  ref=           Branch, tag or SHA to check out"
  echo "  token=         [default: \${{ github.token }}]"
  echo "      Personal access token (PAT) used to fetch the repository."
  echo "  ssh-key=       SSH key used to fetch the repository"
  echo "  fetch-depth=   [default: 1]"
  echo "      Number of commits to fetch. 0 = all history."
  echo "  fetch-tags=    [default: false]"
  echo "      Whether to fetch tags, even if fetch-depth > 0."
  echo "  lfs=           [default: false]"
  echo "      Whether to download Git-LFS files."
  echo "  submodules=    [default: false]"
  echo "      Whether to checkout submodules."
  echo "  clean=         [default: true]"
  echo "      Whether to execute 'git clean' before fetching."
  echo "  persist-credentials=  [default: true]"
  echo "      Whether to configure the token or SSH key in local git config."
  echo "  path=          Relative path under GITHUB_WORKSPACE to checkout."
  echo "  sparse-checkout=  Patterns to use for a sparse checkout."
  echo "  set-safe-directory=  [default: true]"
  echo "  github-server-url=   Override the GitHub server URL."
  echo ""
  echo "Options:"
  echo "  --inputs-json JSON   All inputs as a JSON object string"
  echo "  --inputs-file FILE   YAML or JSON file with inputs (YAML requires yq)"
  echo "  --post               Run the post/cleanup step instead of main"
  echo "  --workspace DIR      Set GITHUB_WORKSPACE (default: cwd)"
  echo "  --env KEY=VALUE      Extra environment variable (repeatable)"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --post)         _post=1; shift ;;
    --workspace)    _workspace="$2"; shift 2 ;;
    --env)          _extra_env+=("$2"); shift 2 ;;
    --inputs-json)  _json_inputs="$2"; shift 2 ;;
    --inputs-file)  _file_inputs="$2"; shift 2 ;;
    --help|-h)      _usage; exit 0 ;;
    *=*)
      # key=value → INPUT_KEY=value  (bash 4+: ^^ = uppercase, //- = replace -)
      _k="${1%%=*}"; _k="${_k^^}"; _k="${_k//-/_}"
      export "INPUT_$_k=${1#*=}"
      shift ;;
    *) echo "Unknown argument: $1" >&2; _usage >&2; exit 1 ;;
  esac
done

# Apply --inputs-json using node (no jq/python needed)
if [[ -n "${_json_inputs:-}" ]]; then
  while IFS= read -r -d $'\0' _pair; do
    export "${_pair%%=*}=${_pair#*=}"
  done < <(
    _JSON_INPUT="$_json_inputs" node -e "
      const inp = JSON.parse(process.env._JSON_INPUT);
      for (const [k, v] of Object.entries(inp)) {
        const key = 'INPUT_' + k.toUpperCase().replace(/-/g, '_');
        process.stdout.write(key + '=' + String(v) + '\0');
      }
    "
  )
fi

# Apply --inputs-file: try JSON via node first, then YAML via yq
if [[ -n "${_file_inputs:-}" ]]; then
  if node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$_file_inputs" 2>/dev/null; then
    while IFS= read -r -d $'\0' _pair; do
      export "${_pair%%=*}=${_pair#*=}"
    done < <(
      _JSON_FILE="$_file_inputs" node -e "
        const inp = JSON.parse(require('fs').readFileSync(process.env._JSON_FILE,'utf8'));
        for (const [k,v] of Object.entries(inp)) {
          const key = 'INPUT_' + k.toUpperCase().replace(/-/g,'_');
          process.stdout.write(key + '=' + String(v) + '\0');
        }
      "
    )
  elif command -v yq &>/dev/null; then
    while IFS= read -r -d $'\0' _pair; do
      export "${_pair%%=*}=${_pair#*=}"
    done < <(
      _JSON_INPUT="$(yq -o json . "$_file_inputs")" node -e "
        const inp = JSON.parse(process.env._JSON_INPUT);
        for (const [k, v] of Object.entries(inp)) {
          const key = 'INPUT_' + k.toUpperCase().replace(/-/g, '_');
          process.stdout.write(key + '=' + String(v) + '\0');
        }
      "
    )
  else
    echo "ERROR: --inputs-file with YAML requires yq (conda install yq)" >&2
    exit 1
  fi
fi

for _kv in "${_extra_env[@]+"${_extra_env[@]}"}"; do
  export "$_kv"
done

# Apply baked-in literal defaults for inputs not yet set
# (Expression defaults like ${{ github.token }} are omitted — supply those explicitly)
: "${INPUT_FETCH_DEPTH:='1'}"
: "${INPUT_FETCH_TAGS:='false'}"
: "${INPUT_SHOW_PROGRESS:='true'}"
: "${INPUT_LFS:='false'}"
: "${INPUT_SUBMODULES:='false'}"
: "${INPUT_SET_SAFE_DIRECTORY:='true'}"
: "${INPUT_SPARSE_CHECKOUT_CONE_MODE:='true'}"
: "${INPUT_PERSIST_CREDENTIALS:='true'}"
: "${INPUT_CLEAN:='true'}"
: "${INPUT_SSH_STRICT:='true'}"
: "${INPUT_SSH_USER:='git'}"

# Set up GITHUB_* environment file sinks
_gh_output="$(mktemp)"
_gh_env="$(mktemp)"
_gh_path="$(mktemp)"
# shellcheck disable=SC2064
trap 'rm -f "$_gh_output" "$_gh_env" "$_gh_path"' EXIT

export GITHUB_WORKSPACE="$_workspace"
export GITHUB_ACTION="$_REPO"
export GITHUB_ACTION_PATH="$ACTION_DIR"
export GITHUB_OUTPUT="$_gh_output"
export GITHUB_ENV="$_gh_env"
export GITHUB_PATH="$_gh_path"
export GITHUB_STEP_SUMMARY=/dev/null
export PATH="$_PREFIX/bin:$PATH"

# Choose main or post script
if [[ "$_post" -eq 1 ]]; then
  if [[ -z "$_POST_SCRIPT" ]]; then
    echo "No post step defined for $_OWNER/$_REPO — nothing to do." >&2
    exit 0
  fi
  _script="$ACTION_DIR/$_POST_SCRIPT"
else
  _script="$ACTION_DIR/$_MAIN_SCRIPT"
fi
if [[ ! -f "$_script" ]]; then
  echo "ERROR: script not found: $_script" >&2
  exit 1
fi

# Run the action
node "$_script"
_exit=$?

# Print any outputs written to GITHUB_OUTPUT
if [[ -s "$_gh_output" ]]; then
  printf '\n--- Action outputs ---\n' >&2
  cat "$_gh_output" >&2
fi

exit $_exit
